version: '3.3'

services:
  db:
    image: postgres:10.1-alpine
  web:
    image: pickmybruin/backend:latest
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    image: pickmybruin/frontend:latest
    ports:
      - "80:80"
    depends_on:
      - web

